server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-165-90-230.compute-1.amazonaws.com:5432/dcque8srbdsm6m
    username: brxzapjsgeeqec
    password: 5c32418ec143f4746b79f84f9d4783979a636465268f5e91d76d2eec2de9a2bd
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema-postgresql.sql