server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-34-236-94-53.compute-1.amazonaws.com:5432/dj0ilic1if2rb
    username: vzzcblbfdfzawe
    password: c41d422640a8cfd1645b2275dda1d01f044f3709f35e1520a9b3987bacd3425a
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    initialize: true
    schema: classpath:/schema-postgresql.sql